services:
  cbioportal:
    restart: unless-stopped
    image: ${CP_DOCKER_IMAGE_CBIOPORTAL}
    container_name: cbioportal-container
    env_file:
      - .env
    environment:
      SERVER_PORT: ${CP_CBIOPORTAL_SERVER_PORT}
      # begin - For backwards compatibility while we make the cbioportal web application "db user aware"
      CLICKHOUSE_USER: ${CP_CLICKHOUSE_USER_FOR_CBIOPORTAL_DB_UPDATE}
      CLICKHOUSE_PASSWORD: ${CP_CLICKHOUSE_PASSWORD_FOR_CBIOPORTAL_DB_UPDATE}
      CLICKHOUSE_HOST: ${CP_CLICKHOUSE_HOST}
      CLICKHOUSE_NATIVE_PORT: ${CP_CLICKHOUSE_NATIVE_INSECURE_PORT}
      CLICKHOUSE_DB: ${CP_CLICKHOUSE_DB}
      CLICKHOUSE_URL: ${CP_CLICKHOUSE_URL}
      CLICKHOUSE_OPTIMIZE_BACKOFF_SECS: ${CP_CLICKHOUSE_OPTIMIZE_BACKOFF_SECS}
      CBIOPORTAL_SERVER_PORT: ${CP_CBIOPORTAL_SERVER_PORT}
      SHOW_DEBUG_INFO: ${CP_SHOW_DEBUG_INFO}
      APPLICATION_PROPERTIES_PATH: ${CP_APPLICATION_PROPERTIES_PATH}
      # end - For backwards compatibility while we make the cbioportal web application "db user aware"
    ports:
      - "${CP_CBIOPORTAL_SERVER_PORT}:${CP_CBIOPORTAL_SERVER_PORT}"
    entrypoint: [ "/cbioportal/entrypoint.sh" ]
    volumes:
      - ./study:/study/
      - ./entrypoint.sh:/cbioportal/entrypoint.sh
      - ${APPLICATION_PROPERTIES_PATH:-./config/application.properties}:/cbioportal-webapp/application.properties:ro
      # We need to mount the derived table script into the cbioportal container
      # The metaImport script looks for it under $PORTAL_HOME
      - ./data/clickhouse.sql:/cbioportal/clickhouse.sql:ro
    depends_on:
      cbioportal-database:
        condition: service_healthy
      cbioportal-session:
        condition: service_started
    networks:
     - cbio-net
    command: /bin/sh -c "java -Xms2g -Xmx4g -cp '/cbioportal-webapp:/cbioportal-webapp/lib/*' org.cbioportal.PortalApplication --spring.config.location=file:/cbioportal-webapp/application.properties --authenticate=false --session.service.url=http://cbioportal-session:${CP_SESSION_SERVICE_SERVER_PORT}/api/sessions/my_portal/ --clickhouse_mode=true --spring.profiles.active=clickhouse"

  cbioportal-database:
    restart: unless-stopped
    image: ${CP_DOCKER_IMAGE_CLICKHOUSE}
    container_name: cbioportal-database-container
    env_file:
      - .env
    ports:
      - ${CP_CLICKHOUSE_HTTP_INSECURE_PORT}:${CP_CLICKHOUSE_HTTP_INSECURE_PORT}
      - ${CP_CLICKHOUSE_HTTP_SECURE_PORT}:${CP_CLICKHOUSE_HTTP_SECURE_PORT}
      - ${CP_CLICKHOUSE_NATIVE_INSECURE_PORT}:${CP_CLICKHOUSE_NATIVE_INSECURE_PORT}
      - ${CP_CLICKHOUSE_NATIVE_SECURE_PORT}:${CP_CLICKHOUSE_NATIVE_SECURE_PORT}
    volumes:
      - ./data/schema.sql:/data/schema.sql:ro
      - ./data/seed.sql.gz:/data/seed.sql.gz:ro
      - ./data/clickhouse.sql:/data/clickhouse.sql:ro
      - .${CP_CLICKHOUSE_CLIENT_EXTERNAL_CONFIG_FOR_WEB_APP_PATH}:${CP_CLICKHOUSE_CLIENT_EXTERNAL_CONFIG_FOR_WEB_APP_PATH}:rw
      - .${CP_CLICKHOUSE_CLIENT_EXTERNAL_CONFIG_FOR_DB_UPDATE_PATH}:${CP_CLICKHOUSE_CLIENT_EXTERNAL_CONFIG_FOR_DB_UPDATE_PATH}:rw
      - .${CP_CLICKHOUSE_CLIENT_EXTERNAL_CONFIG_FOR_DB_ADMIN_PATH}:${CP_CLICKHOUSE_CLIENT_EXTERNAL_CONFIG_FOR_DB_ADMIN_PATH}:rw
      - ./data/write_clickhouse_client_config_files.sh:/docker-entrypoint-initdb.d/001_write_clickhouse_client_config_files.sh:ro
      - ./data/create_cbioportal_database.sh:/docker-entrypoint-initdb.d/002_create_cbioportal_database.sh:ro
      - ./data/create_cbio_users_and_grant_privileges.sh:/docker-entrypoint-initdb.d/003_create_users_and_write_privileges.sh:ro
      - ./data/load_schema.sh:/docker-entrypoint-initdb.d/004_load_schema.sh:ro
      - ./data/load_seed.sh:/docker-entrypoint-initdb.d/005_load_seed.sh:ro
      - ./data/load_derived_tables.sh:/docker-entrypoint-initdb.d/006_load_derived_tables.sh:ro
      - cbioportal_clickhouse_data:/var/lib/clickhouse
    networks:
      - cbio-net
    healthcheck:
      test: ["CMD-SHELL", "clickhouse client --config-file=.${CP_CLICKHOUSE_CLIENT_EXTERNAL_CONFIG_FOR_DB_UPDATE_PATH} --query=\"SELECT COUNT(*) FROM $$CP_CLICKHOUSE_DB.type_of_cancer\" 2>/dev/null | grep -q '^[1-9]'"]
      interval: 10s
      timeout: 3s
      retries: 300
      start_period: 5m

  cbioportal-session:
    restart: unless-stopped
    image: ${CP_DOCKER_IMAGE_SESSION_SERVICE}
    container_name: cbioportal-session-container
    env_file:
      - .env
    environment:
      SERVER_PORT: ${CP_SESSION_SERVICE_SERVER_PORT}
      JAVA_OPTS: ${CP_SESSION_SERVICE_JAVA_OPTS}
    depends_on:
      - cbioportal-session-database
    networks:
      - cbio-net

  cbioportal-session-database:
    restart: unless-stopped
    image: mongo:4.2
    container_name: cbioportal-session-database-container
    env_file:
      - .env
    volumes:
      - cbioportal_mongo_data:/data/db
    networks:
      - cbio-net

networks:
  cbio-net:

volumes:
  cbioportal_clickhouse_data:
  cbioportal_mongo_data:
  sql-files:
