#!/usr/bin/env python3
"""Export a complete, de-identified Databricks WSI snapshot for a study.

The portal study files define the cohort.  Databricks owns the canonical WSI
associations and thumbnail registry, so this exporter performs one bulk SQL
read, filters rows to the study's patient/sample identifiers, and writes the
portal ``meta_wsi.txt``/``data_wsi.txt`` contract.  It intentionally reads the
de-identified canonical table only; PHI tables are never queried.  Canonical
associations that are explicitly marked ``can_serve_tiles = false`` are kept
as non-servable provenance (including matched BLOCK/PART rows); only rows
marked servable are allowed to fail the complete-pixel contract.

Exports fail closed when Databricks marks a row as tile-servable but its
published registry record is missing source, thumbnail, or validated tile
metadata.  Explicitly non-servable associations remain in the hierarchy with
empty pixel fields so timeline counts and pathology provenance are preserved.
``--allow-incomplete-assets`` is reserved for diagnostics and must not be used
for an accepted study release.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import time
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import urlparse

# Timeline study files are generated by the tile-server package so the WSI
# exporter and the standalone timeline exporter share exactly the same
# grouping, de-identification, and linkout rules.  Keep this import optional
# for callers that only use the pure WSI row helpers in a compose checkout.
_TILE_SERVER_ROOT = Path(__file__).resolve().parents[2] / "cbioportal-tile-server"
if _TILE_SERVER_ROOT.is_dir() and str(_TILE_SERVER_ROOT) not in sys.path:
    sys.path.insert(0, str(_TILE_SERVER_ROOT))
try:  # pragma: no cover - exercised by the integration exporter
    from tools.generate_pathology_timeline_files import (
        build_pathology_timeline_rows,
        write_pathology_timeline_files,
    )
except ModuleNotFoundError:  # pure compose unit tests/checkouts
    build_pathology_timeline_rows = None
    write_pathology_timeline_files = None


DATA_COLUMNS = (
    "PATIENT_ID", "REFERENCE_SAMPLE_ID", "SAMPLE_ID", "IMAGE_ID",
    "PART_KEY", "PART_NUMBER", "PART_DESIGNATOR", "PART_TYPE",
    "PART_DESCRIPTION", "SUBSPECIALTY", "PATH_DX_TITLE", "BLOCK_KEY",
    "BLOCK_NUMBER", "BLOCK_LABEL", "MATCH_LEVEL", "SPECIMEN_KEY",
    "STAIN_NAME", "STAIN_GROUP", "IS_HNE", "IS_IHC", "MAGNIFICATION",
    "FILE_SIZE_BYTES", "BARCODE", "SLIDE_TYPE", "CAN_SERVE_TILES",
    "SOURCE_URL", "TILE_METADATA_JSON", "THUMBNAIL_URL", "THUMBNAIL_WIDTH",
    "THUMBNAIL_HEIGHT", "THUMBNAIL_CONTENT_TYPE",
)
TIMELINE_COLUMNS = (
    "timeline_start_days",
    "timeline_date_status",
    "slide_timepoint_source",
)

_DESCRIPTIONS = {
    "PATIENT_ID": "cBioPortal patient stable identifier.",
    "REFERENCE_SAMPLE_ID": "Optional patient reference sample stable identifier.",
    "SAMPLE_ID": "Matched cBioPortal sample stable identifier; empty for unmatched slides.",
    "IMAGE_ID": "Stable whole-slide image identifier, unique within the study.",
    "PART_KEY": "Stable pathology part key within the patient.",
    "PART_NUMBER": "Source pathology part number.",
    "PART_DESIGNATOR": "Source pathology part designator.",
    "PART_TYPE": "Pathology part type.",
    "PART_DESCRIPTION": "Pathology part description.",
    "SUBSPECIALTY": "Pathology subspecialty.",
    "PATH_DX_TITLE": "Pathology diagnosis.",
    "BLOCK_KEY": "Stable pathology block key within the part.",
    "BLOCK_NUMBER": "Source pathology block number.",
    "BLOCK_LABEL": "Human-readable pathology block label.",
    "MATCH_LEVEL": "Slide association level: BLOCK, PART, or UNMATCHED.",
    "SPECIMEN_KEY": "Stable key used to select this pathology specimen.",
    "STAIN_NAME": "Canonical stain name.",
    "STAIN_GROUP": "Canonical stain group.",
    "IS_HNE": "Whether the slide is H&E.",
    "IS_IHC": "Whether the slide is immunohistochemistry.",
    "MAGNIFICATION": "Scanner or source magnification.",
    "FILE_SIZE_BYTES": "Source slide size in bytes.",
    "BARCODE": "Slide barcode, when available.",
    "SLIDE_TYPE": "Normalized slide type.",
    "CAN_SERVE_TILES": "Whether source-bound pixel artifacts are complete.",
    "SOURCE_URL": "Exact source URL supplied to the tile server.",
    "TILE_METADATA_JSON": "Tile-pyramid metadata consumed by the browser.",
    "THUMBNAIL_URL": "Pre-rendered thumbnail source URL.",
    "THUMBNAIL_WIDTH": "Intrinsic thumbnail width in pixels.",
    "THUMBNAIL_HEIGHT": "Intrinsic thumbnail height in pixels.",
    "THUMBNAIL_CONTENT_TYPE": "Thumbnail media type.",
}

_INTEGER_COLUMNS = {"FILE_SIZE_BYTES", "THUMBNAIL_WIDTH", "THUMBNAIL_HEIGHT"}
_BOOLEAN_COLUMNS = {"IS_HNE", "IS_IHC", "CAN_SERVE_TILES"}
_SOURCE_PREFIX_ENV = "WSI_ALLOWED_SOURCE_PREFIXES"
# Keep a narrow default for callers that use the pure row helper without a
# deployment environment.  Production/e2e invocations must provide the same
# approved-prefix list used by the tile server through WSI_ALLOWED_SOURCE_PREFIXES
# (or --allowed-source-prefix).  This prevents the exporter and pixel service
# from disagreeing about which S3 locations are actually servable.
_DEFAULT_SOURCE_PREFIXES = ("s3://mskmind-bkt/reef-slides/",)
_THUMBNAIL_PREFIX = "s3://mskmind-bkt/wsi-thumbnails/"
_DEID_DATE_PATTERNS = (
    re.compile(r'(?<!\d)(?:19|20)\d{2}[-_/](?:0?[1-9]|1[0-2])[-_/](?:0?[1-9]|[12]\d|3[01])(?!\d)'),
    re.compile(r'(?<!\d)(?:0?[1-9]|1[0-2])[-_/](?:0?[1-9]|[12]\d|3[01])[-_/](?:19|20)\d{2}(?!\d)'),
    re.compile(r'(?<!\d)(?:0?[1-9]|[12]\d|3[01])[-_/](?:0?[1-9]|1[0-2])[-_/](?:19|20)\d{2}(?!\d)'),
    re.compile(r'(?i)(?<![a-z0-9])(?:(?:jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t(?:ember)?)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)\s+(?:0?[1-9]|[12]\d|3[01])(?:st|nd|rd|th)?(?:,)?\s+(?:19|20)\d{2})(?![a-z0-9])'),
    re.compile(r'(?<!\d)(?:19|20)\d{6}(?!\d)'),
)
_DEID_MRN = re.compile(r'(?i)\b(?:mrn|medical[ _-]?record(?:[ _-]?number)?)\b\s*[:=#-]?\s*\d{4,}')


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--study-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument(
        "--warehouse-id",
        default=os.environ.get("DATABRICKS_WAREHOUSE_ID", "0b49b7d78734ad5c"),
    )
    parser.add_argument(
        "--canonical-table",
        default="cdsi_prod.pathology_data_mining.canonical_slide_associations",
    )
    parser.add_argument(
        "--registry-table",
        default="cdsi_prod.pathology_data_mining.slide_thumbnail_registry",
    )
    parser.add_argument(
        "--allowed-source-prefix",
        dest="allowed_source_prefixes",
        action="append",
        help=(
            "Approved S3 source URI prefix. Repeat for every prefix accepted "
            "by the tile server; defaults to WSI_ALLOWED_SOURCE_PREFIXES."
        ),
    )
    parser.add_argument(
        "--allow-incomplete-assets",
        action="store_true",
        help=(
            "diagnostic-only escape hatch: retain non-servable rows when the "
            "registry has not hydrated every canonical asset. Normal exports "
            "fail closed so a partial WSI release cannot be published."
        ),
    )
    return parser.parse_args()


def _source_prefixes(values: Iterable[str] | None = None) -> tuple[str, ...]:
    """Return validated S3 source prefixes shared with the tile service.

    The tile server owns the publication boundary.  The exporter must use the
    same explicit prefix list instead of assuming that every source lives in
    the reef-slides prefix.  Non-S3 entries (for example the local test-data
    prefix used by docker compose) are intentionally ignored here because the
    Databricks contract only emits S3 source URLs.
    """
    if values is None:
        raw = os.environ.get(_SOURCE_PREFIX_ENV, "")
        values = raw.split(",") if raw.strip() else _DEFAULT_SOURCE_PREFIXES

    prefixes: list[str] = []
    for raw_value in values:
        value = str(raw_value or "").strip()
        if not value:
            continue
        parsed = urlparse(value)
        if parsed.scheme.lower() != "s3":
            continue
        # A bucket-root prefix such as ``s3://ocra/`` is valid and is used by
        # the source inventory. Keep rejecting malformed/non-S3 values, but
        # do not require an object path after the bucket name.
        if not parsed.netloc or not parsed.path.startswith("/"):
            raise ValueError(
                f"{_SOURCE_PREFIX_ENV} contains an invalid S3 prefix: {value}"
            )
        if not value.endswith("/"):
            value += "/"
        if value not in prefixes:
            prefixes.append(value)
    if not prefixes:
        raise ValueError(
            f"{_SOURCE_PREFIX_ENV} must contain at least one valid S3 prefix"
        )
    return tuple(prefixes)


def _read_ids(study_dir: Path) -> tuple[str, set[str], set[str], dict[str, str]]:
    patient_ids: set[str] = set()
    sample_ids: set[str] = set()
    sample_to_patient: dict[str, str] = {}
    sample_file = study_dir / "data_clinical_sample.txt"
    if not sample_file.is_file():
        raise FileNotFoundError(sample_file)
    with sample_file.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader((line for line in handle if not line.startswith("#")), delimiter="\t")
        for row in reader:
            patient = (row.get("PATIENT_ID") or "").strip()
            sample = (row.get("SAMPLE_ID") or "").strip()
            if patient:
                patient_ids.add(patient)
            if sample:
                sample_ids.add(sample)
                if patient:
                    sample_to_patient[sample] = patient
    if not patient_ids or not sample_ids:
        raise ValueError("study sample file contains no patient/sample identifiers")
    study_id = study_dir.name
    meta = study_dir / "meta_study.txt"
    if meta.is_file():
        for line in meta.read_text(encoding="utf-8").splitlines():
            if line.startswith("cancer_study_identifier:"):
                study_id = line.split(":", 1)[1].strip()
                break
    return study_id, patient_ids, sample_ids, sample_to_patient


def _query_sql(canonical: str, registry: str) -> str:
    # Identifiers are validated here because they are interpolated into SQL.
    for identifier in (canonical, registry):
        if not identifier.replace("_", "").replace(".", "").isalnum() or identifier.count(".") != 2:
            raise ValueError(f"invalid Databricks table identifier: {identifier}")
    return f"""
WITH ranked_registry AS (
    SELECT CAST(image_id AS STRING) AS image_id, source_path, artifact_uri,
           width, height, content_type, tile_metadata_json,
           serving_artifact_uri, serving_width, serving_height,
           ROW_NUMBER() OVER (
               PARTITION BY CAST(image_id AS STRING), source_path
               ORDER BY rendered_at DESC, manifest_version DESC
           ) AS rn
    FROM {registry}
    WHERE status = 'success'
)
SELECT c.patient_id, c.reference_sample_id, c.sample_id, c.match_level,
       c.image_id, c.part_key, c.part_number, c.part_designator, c.part_type,
       c.part_description, c.subspecialty, c.path_dx_title, c.block_key,
       c.block_number, c.block_label, c.stain_name, c.stain_group, c.is_hne,
       c.is_ihc, c.magnification, c.file_size_bytes, c.barcode, c.slide_type,
       c.specimen_key, c.can_serve_tiles, c.slide_path,
       c.timeline_start_days, c.timeline_date_status,
       NULL AS slide_timepoint_source,
       r.tile_metadata_json, r.artifact_uri, r.width, r.height,
       r.content_type, r.serving_artifact_uri, r.serving_width, r.serving_height
FROM {canonical} c
LEFT JOIN ranked_registry r
  ON CAST(c.image_id AS STRING) = r.image_id
 AND c.slide_path = r.source_path
 AND r.rn = 1
WHERE c.patient_id LIKE 'P-%'
"""


def _legacy_query_sql(canonical: str, registry: str) -> str:
    """Build the same export query for a pre-migration canonical table."""
    query = _query_sql(canonical, registry)
    query = query.replace(
        "c.timeline_start_days, c.timeline_date_status,\n       NULL AS slide_timepoint_source,",
        "c.procedure_date_days AS timeline_start_days, "
        "CASE WHEN c.procedure_date_days IS NOT NULL THEN 'AVAILABLE' "
        "ELSE 'MISSING_PROCEDURE_DATE' END AS timeline_date_status, "
        "c.timepoint_source AS slide_timepoint_source,",
    )
    return query


def _run_external_query(sql: str, warehouse_id: str) -> Iterable[dict[str, Any]]:
    from databricks.sdk import WorkspaceClient
    from databricks.sdk.service.sql import Disposition, Format, StatementState
    from urllib.request import Request, urlopen

    client = WorkspaceClient()
    statement = client.statement_execution.execute_statement(
        warehouse_id=warehouse_id,
        statement=sql,
        disposition=Disposition.EXTERNAL_LINKS,
        format=Format.JSON_ARRAY,
        wait_timeout="50s",
    )
    started = time.monotonic()
    while statement.status.state in (StatementState.PENDING, StatementState.RUNNING):
        if time.monotonic() - started > 600:
            client.statement_execution.cancel_execution(statement.statement_id)
            raise TimeoutError("Databricks WSI query exceeded ten minutes")
        time.sleep(2)
        statement = client.statement_execution.get_statement(statement.statement_id)
    if statement.status.state != StatementState.SUCCEEDED:
        raise RuntimeError(f"Databricks WSI query failed: {getattr(statement.status, 'error', None)}")
    columns = [column.name for column in statement.manifest.schema.columns]
    for chunk_index in range(int(statement.manifest.total_chunk_count or 0)):
        chunk = client.statement_execution.get_statement_result_chunk_n(statement.statement_id, chunk_index)
        links = chunk.external_links or []
        if not links:
            continue
        link = links[0]
        request = Request(link.external_link, headers=link.http_headers or {})
        with urlopen(request, timeout=180) as response:  # noqa: S310 - signed Databricks link
            payload = json.loads(response.read().decode("utf-8"))
        for values in payload:
            yield dict(zip(columns, values))


def _run_export_query(
    canonical: str, registry: str, warehouse_id: str
) -> Iterable[dict[str, Any]]:
    """Read the current contract, retrying once against a pre-migration table.

    Databricks reports unresolved columns only after statement execution.  The
    query is therefore wrapped as a generator: no partial rows are yielded
    before the statement succeeds, so the legacy retry cannot duplicate data.
    """
    try:
        yield from _run_external_query(_query_sql(canonical, registry), warehouse_id)
    except RuntimeError as error:
        message = str(error).lower()
        if "timeline_start_days" not in message and "timeline_date_status" not in message:
            raise
        yield from _run_external_query(
            _legacy_query_sql(canonical, registry), warehouse_id
        )


def _text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    value = str(value)
    # The published canonical table is de-identified, but a few pathology
    # descriptions retain line breaks from the source report.  Study TSVs
    # cannot contain those delimiters, so normalize all whitespace to a space.
    return " ".join(value.split())


def _deid_text(value: Any) -> str:
    """Normalize free text and redact dates/MRN-like labels before publishing."""
    text = _text(value)
    text = _DEID_MRN.sub("[REDACTED_MRN]", text)
    for pattern in _DEID_DATE_PATTERNS:
        text = pattern.sub("[REDACTED_DATE]", text)
    return text


def _safe_key(value: Any, fallback: str) -> str:
    text = _deid_text(value).replace("?", "unknown")
    text = re.sub(r"[^A-Za-z0-9_.:/-]+", "_", text).strip("_")
    return text or fallback


def _metadata_is_safe_and_valid(value: Any) -> bool:
    if not isinstance(value, dict):
        return False
    allowed = {
        "dimensions", "levels", "level_dimensions", "level_downsamples", "max_zoom",
        "tile_size", "mpp", "objective_power", "vendor", "identity_version", "safe_min_level",
        "tile_metadata_schema_version", "decode_policy_version", "max_decode_pixels",
        "thumbnail_max_decode_pixels", "source_fingerprint",
    }
    if set(value) - allowed:
        return False
    dimensions = value.get("dimensions")
    levels = value.get("levels")
    level_dimensions = value.get("level_dimensions")
    if not isinstance(dimensions, dict) or not isinstance(levels, int) or levels <= 0:
        return False
    if not all(type(dimensions.get(name)) is int and dimensions[name] > 0 for name in ("width", "height")):
        return False
    if not isinstance(level_dimensions, list) or len(level_dimensions) != levels:
        return False
    if any(not isinstance(level, dict) or not all(type(level.get(name)) is int and level[name] > 0 for name in ("width", "height")) for level in level_dimensions):
        return False
    if not isinstance(value.get("max_zoom"), int) or value["max_zoom"] < 0:
        return False
    if not isinstance(value.get("tile_size"), int) or value["tile_size"] <= 0:
        return False

    def contains_sensitive_text(child: Any, *, key: str | None = None) -> bool:
        # ``source_fingerprint`` is a SHA-256 digest, not free text.  A
        # digest can legitimately contain an eight-digit substring that looks
        # like YYYYMMDD; applying the date detector to it creates a false
        # positive and rejects an otherwise valid serving contract.  Validate
        # its shape below instead of treating it as de-identification text.
        if key == "source_fingerprint":
            return False
        if isinstance(child, str):
            return bool(_DEID_MRN.search(child) or any(pattern.search(child) for pattern in _DEID_DATE_PATTERNS))
        if isinstance(child, dict):
            return any(contains_sensitive_text(item, key=str(name)) for name, item in child.items())
        if isinstance(child, list):
            return any(contains_sensitive_text(item) for item in child)
        return False
    fingerprint = value.get("source_fingerprint")
    if fingerprint is not None:
        if not isinstance(fingerprint, str) or not re.fullmatch(r"[0-9a-fA-F]{64}", fingerprint):
            return False
    return not contains_sensitive_text(value)


def _bool(value: Any) -> str:
    return "TRUE" if str(value).strip().lower() in {"1", "true", "yes"} else "FALSE"


def _int(value: Any) -> str:
    return "" if value in (None, "") else str(int(value))


def _row(
    record: dict[str, Any],
    patients: set[str],
    samples: set[str],
    sample_to_patient: dict[str, str],
    *,
    require_complete_assets: bool,
    asset_stats: dict[str, int],
    allowed_source_prefixes: tuple[str, ...] | None = None,
) -> list[str] | None:
    patient = _text(record.get("patient_id"))
    sample = _text(record.get("sample_id"))
    reference = _text(record.get("reference_sample_id"))
    match_level = _text(record.get("match_level")).upper()
    if patient not in patients:
        return None
    if sample and sample_to_patient.get(sample) != patient:
        sample = ""
    if reference and sample_to_patient.get(reference) != patient:
        reference = ""
    if match_level in ("BLOCK", "PART") and not sample:
        # Keep the slide and its pathology provenance when the canonical
        # association points at a sample that is not part of this study's
        # clinical-sample file.  Clearing the sample avoids attaching it to a
        # different specimen; downgrading the association to UNMATCHED keeps
        # the image visible (and still servable when its pixel bundle exists)
        # instead of silently filtering a cohort row.
        match_level = "UNMATCHED"
    if match_level not in ("BLOCK", "PART", "UNMATCHED"):
        return None
    if match_level == "UNMATCHED":
        sample = ""
    elif sample not in samples:
        return None
    image = _text(record.get("image_id"))
    if not image:
        raise ValueError("canonical WSI row has no image_id")
    source = _text(record.get("slide_path"))
    tile_metadata = record.get("tile_metadata_json")
    try:
        tile_metadata_value = json.loads(tile_metadata) if tile_metadata else None
    except (TypeError, ValueError):
        tile_metadata_value = None
    # Publish the stable master artifact.  Versioned navigation pointers are
    # useful inside the registry, but their timestamped path segments look
    # like compact dates to the cBioPortal study-file validator and are not
    # needed by the portal (the tile service can resize the master on demand).
    artifact = _text(record.get("artifact_uri")) or _text(record.get("serving_artifact_uri"))
    artifact_is_master = bool(_text(record.get("artifact_uri")))
    canonical_can_serve = str(record.get("can_serve_tiles")).lower() in {"true", "1"}
    source_is_allowed = any(source.startswith(prefix) for prefix in (allowed_source_prefixes or _source_prefixes()))
    if canonical_can_serve:
        asset_stats["canonical_servable"] = asset_stats.get("canonical_servable", 0) + 1
    can_serve = (
        canonical_can_serve
        and source_is_allowed
        and artifact.startswith(_THUMBNAIL_PREFIX)
        and _metadata_is_safe_and_valid(tile_metadata_value)
    )
    # Explicitly non-servable associations are retained as provenance even
    # when they are matched to a BLOCK/PART.  A source may be absent from the
    # inventory, or the source may be known to be unreadable; either case is
    # represented by CAN_SERVE_TILES=FALSE and must not erase the hierarchy.
    if require_complete_assets and canonical_can_serve and not can_serve:
        asset_stats["incomplete"] = asset_stats.get("incomplete", 0) + 1
        missing: list[str] = []
        if not source_is_allowed:
            missing.append("source_url")
        if not artifact.startswith(_THUMBNAIL_PREFIX):
            missing.append("thumbnail_url")
        if not _metadata_is_safe_and_valid(tile_metadata_value):
            missing.append("tile_metadata_json")
        raise ValueError(
            "canonical WSI asset contract "
            f"is incomplete for image {image}: {', '.join(missing)}"
        )
    if canonical_can_serve and not can_serve:
        asset_stats["incomplete"] = asset_stats.get("incomplete", 0) + 1
    values: list[str] = []
    values.extend((_text(patient), _text(reference), _text(sample), image))
    part_key = _safe_key(record.get("part_key"), "part:unknown")
    block_key = _safe_key(record.get("block_key"), "block:unknown")
    values.extend((part_key,))
    values.extend(_deid_text(record.get(field)) for field in ("part_number", "part_designator", "part_type", "part_description", "subspecialty", "path_dx_title"))
    values.extend((block_key, _deid_text(record.get("block_number")), _deid_text(record.get("block_label")), match_level))
    values.extend((f"{match_level.lower()}::{part_key}::{block_key}", _deid_text(record.get("stain_name")), _deid_text(record.get("stain_group"))))
    values.extend((_bool(record.get("is_hne")), _bool(record.get("is_ihc")), _deid_text(record.get("magnification"))))
    values.append(_int(record.get("file_size_bytes")))
    values.extend((
        _deid_text(record.get("barcode")),
        _deid_text(record.get("slide_type")),
        "TRUE" if can_serve else "FALSE",
        source if can_serve else "",
        json.dumps(tile_metadata_value, separators=(",", ":"), sort_keys=True) if can_serve else "",
        artifact if can_serve else "",
        _int((record.get("width") if artifact_is_master else record.get("serving_width")) or record.get("width")) if can_serve else "",
        _int((record.get("height") if artifact_is_master else record.get("serving_height")) or record.get("height")) if can_serve else "",
        _deid_text(record.get("content_type")) if can_serve else "",
    ))
    if len(values) != len(DATA_COLUMNS):
        raise AssertionError(f"unexpected WSI column count {len(values)}")
    return values


def _write(study_id: str, output_dir: Path, rows: Iterable[list[str]], stats: dict[str, Any]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    meta_path = output_dir / "meta_wsi.txt"
    data_path = output_dir / "data_wsi.txt"
    manifest_path = output_dir / "wsi_snapshot_manifest.json"
    tmp_data = data_path.with_suffix(".txt.tmp")
    meta_path.write_text("\n".join((f"cancer_study_identifier: {study_id}", "genetic_alteration_type: PATHOLOGY_SLIDES", "datatype: WSI", "data_filename: data_wsi.txt", "format_version: 2", "")), encoding="utf-8")
    with tmp_data.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n", quoting=csv.QUOTE_NONE, quotechar=None)
        writer.writerow([f"#{name}" for name in DATA_COLUMNS])
        writer.writerow([f"#{_DESCRIPTIONS[name]}" for name in DATA_COLUMNS])
        writer.writerow(["#BOOLEAN" if name in _BOOLEAN_COLUMNS else "#NUMBER" if name in _INTEGER_COLUMNS else "#STRING" for name in DATA_COLUMNS])
        writer.writerow(["#0"] * len(DATA_COLUMNS))
        writer.writerow(DATA_COLUMNS)
        for values in rows:
            writer.writerow(values)
    os.replace(tmp_data, data_path)
    manifest = {
        "study_id": study_id,
        "association_row_count": stats["rows"],
        "servable_row_count": stats["servable"],
        "patient_count": stats["patients"],
        "duplicate_association_count": stats.get("duplicates", 0),
        "canonical_servable_row_count": stats.get("canonical_servable", 0),
        "incomplete_asset_count": stats.get("incomplete", 0),
        "cohort_rows_seen": stats.get("cohort_rows_seen", 0),
        "filtered_row_count": stats.get("filtered_rows", 0),
        "timeline_event_count": stats.get("timeline_events", 0),
        "source": "Databricks de-identified canonical_slide_associations",
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def _timeline_record(values: list[str]) -> dict[str, Any]:
    """Convert an exported WSI row (including its private timing tail) back
    into the association shape consumed by the shared timeline formatter."""
    def value(name: str) -> str:
        return values[DATA_COLUMNS.index(name)]

    timing_offset = len(DATA_COLUMNS)
    return {
        "patient_id": value("PATIENT_ID"),
        "sample_id": value("SAMPLE_ID") or None,
        "match_level": value("MATCH_LEVEL"),
        "image_id": value("IMAGE_ID"),
        "part_key": value("PART_KEY"),
        "part_number": value("PART_NUMBER") or None,
        "block_key": value("BLOCK_KEY"),
        "block_number": value("BLOCK_NUMBER") or None,
        "block_label": value("BLOCK_LABEL") or None,
        "part_description": value("PART_DESCRIPTION") or None,
        "stain_name": value("STAIN_NAME") or None,
        "stain_group": value("STAIN_GROUP") or None,
        "is_hne": value("IS_HNE") == "TRUE",
        "is_ihc": value("IS_IHC") == "TRUE",
        "slide_path": value("SOURCE_URL"),
        "can_serve_tiles": value("CAN_SERVE_TILES") == "TRUE",
        "specimen_key": value("SPECIMEN_KEY"),
        "timeline_start_days": values[timing_offset] or None,
        "timeline_date_status": values[timing_offset + 1] or None,
        "slide_timepoint_source": values[timing_offset + 2] or None,
    }


def main() -> int:
    args = _parse_args()
    allowed_source_prefixes = _source_prefixes(args.allowed_source_prefixes)
    study_dir = args.study_dir.resolve()
    output_dir = (args.output_dir or study_dir).resolve()
    study_id, patients, samples, sample_to_patient = _read_ids(study_dir)
    output_by_image: dict[str, list[str]] = {}
    asset_stats = {"canonical_servable": 0, "incomplete": 0}
    duplicate_count = 0
    scanned = 0
    for record in _run_export_query(
        args.canonical_table, args.registry_table, args.warehouse_id
    ):
        scanned += 1
        in_requested_study = _text(record.get("patient_id")) in patients
        if in_requested_study:
            asset_stats["cohort_rows_seen"] = asset_stats.get("cohort_rows_seen", 0) + 1
        values = _row(
            record,
            patients,
            samples,
            sample_to_patient,
            require_complete_assets=not args.allow_incomplete_assets,
            asset_stats=asset_stats,
            allowed_source_prefixes=allowed_source_prefixes,
        )
        if values is None:
            if in_requested_study:
                asset_stats["filtered_rows"] = asset_stats.get("filtered_rows", 0) + 1
            continue
        image = values[DATA_COLUMNS.index("IMAGE_ID")]
        previous = output_by_image.get(image)
        # Keep the timing fields alongside the selected WSI association.  They
        # are private exporter state and are removed before data_wsi.txt is
        # written; the cBioPortal WSI contract never exposes procedure dates.
        values.extend(
            str(record.get(field) or "") for field in TIMELINE_COLUMNS
        )
        if previous is not None:
            duplicate_count += 1
            # A slide can have more than one canonical association.  The
            # portal WSI file has one row per image, so retain the strongest
            # association and prefer a sample-linked/servable row on ties.
            rank = {"BLOCK": 0, "PART": 1, "UNMATCHED": 2}
            current_key = (
                rank.get(values[DATA_COLUMNS.index("MATCH_LEVEL")], 3),
                0 if values[DATA_COLUMNS.index("SAMPLE_ID")] else 1,
                0 if values[DATA_COLUMNS.index("CAN_SERVE_TILES")] == "TRUE" else 1,
                values[DATA_COLUMNS.index("PATIENT_ID")],
                values[DATA_COLUMNS.index("SAMPLE_ID")],
            )
            previous_key = (
                rank.get(previous[DATA_COLUMNS.index("MATCH_LEVEL")], 3),
                0 if previous[DATA_COLUMNS.index("SAMPLE_ID")] else 1,
                0 if previous[DATA_COLUMNS.index("CAN_SERVE_TILES")] == "TRUE" else 1,
                previous[DATA_COLUMNS.index("PATIENT_ID")],
                previous[DATA_COLUMNS.index("SAMPLE_ID")],
            )
            if current_key < previous_key:
                output_by_image[image] = values
        else:
            output_by_image[image] = values
        if scanned % 100_000 == 0:
            print(f"scanned {scanned:,} canonical rows; retained {len(output_by_image):,}", file=sys.stderr, flush=True)
    output_rows = list(output_by_image.values())
    if not args.allow_incomplete_assets and asset_stats.get("filtered_rows", 0):
        raise ValueError(
            "the Databricks WSI export filtered "
            f"{asset_stats['filtered_rows']} rows belonging to the requested "
            "study cohort; refusing to publish a partial WSI study"
        )
    if not output_rows:
        raise ValueError("Databricks query returned no rows for the study cohort")
    # Canonical associations occasionally disagree on descriptive part/block
    # metadata. Pick one deterministic value per hierarchy key so the portal
    # can render a consistent tree while retaining every unique image.
    output_rows.sort(key=lambda row: tuple(row[: len(DATA_COLUMNS)]))
    part_indexes = [4, 5, 6, 7, 8, 9, 10]
    block_indexes = [12, 13]
    part_values: dict[tuple[str, str], tuple[str, ...]] = {}
    block_values: dict[tuple[str, str, str], tuple[str, ...]] = {}
    for row in output_rows:
        part_key = (row[0], row[4])
        part_values.setdefault(part_key, tuple(row[index] for index in part_indexes))
        block_key = (row[0], row[4], row[11])
        block_values.setdefault(block_key, tuple(row[index] for index in block_indexes))
    for row in output_rows:
        part_key = (row[0], row[4])
        block_key = (row[0], row[4], row[11])
        for index, value in zip(part_indexes, part_values[part_key]):
            row[index] = value
        for index, value in zip(block_indexes, block_values[block_key]):
            row[index] = value
        row[15] = f"{row[14].lower()}::{row[4]}::{row[11]}"
    output_rows.sort(key=lambda row: (row[0], row[3]))
    servable = sum(row[DATA_COLUMNS.index("CAN_SERVE_TILES")] == "TRUE" for row in output_rows)
    if not args.allow_incomplete_assets and servable == 0:
        raise ValueError(
            "the requested study has no servable WSI assets after hydration; "
            "refusing to publish an empty WSI viewer"
        )
    if write_pathology_timeline_files is None or build_pathology_timeline_rows is None:
        raise RuntimeError(
            "the shared pathology timeline exporter is unavailable; refusing "
            "to publish a WSI snapshot without timeline data"
        )
    timeline_records = [_timeline_record(row) for row in output_rows]
    timeline_rows = build_pathology_timeline_rows(timeline_records, study_id)
    if not timeline_rows:
        raise ValueError(
            "the requested study has no dated pathology associations; refusing "
            "to publish a WSI snapshot without timeline events"
        )
    timeline_meta, timeline_data, timeline_event_count = write_pathology_timeline_files(
        output_dir, study_id, timeline_records
    )
    # Strip the private timing tail before serializing the WSI table.
    wsi_rows = [row[: len(DATA_COLUMNS)] for row in output_rows]
    servable_patients = {row[DATA_COLUMNS.index("PATIENT_ID")] for row in output_rows if row[DATA_COLUMNS.index("CAN_SERVE_TILES")] == "TRUE"}
    _write(
        study_id,
        output_dir,
        wsi_rows,
        {
            "rows": len(output_rows),
            "servable": servable,
            "patients": len({row[0] for row in output_rows}),
            "duplicates": duplicate_count,
            "canonical_servable": asset_stats["canonical_servable"],
            "incomplete": asset_stats["incomplete"],
            "cohort_rows_seen": asset_stats.get("cohort_rows_seen", 0),
            "filtered_rows": asset_stats.get("filtered_rows", 0),
            "timeline_events": timeline_event_count,
        },
    )
    print(json.dumps({"study_id": study_id, "canonical_rows_scanned": scanned, "rows": len(wsi_rows), "duplicates": duplicate_count, "servable": servable, "patients": len({row[0] for row in wsi_rows}), "servable_patients": len(servable_patients), "timeline_events": timeline_event_count, "timeline_meta": str(timeline_meta), "timeline_data": str(timeline_data), "output_dir": str(output_dir)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
