#!/usr/bin/env python3
"""Reconcile pathology timeline counts with the final WSI capability file.

The timeline and WSI files are often generated by separate import jobs.  This
utility is the safe bridge for an existing release: it uses the public WSI
contract as the source of truth for ``CAN_SERVE_TILES`` and rewrites only the
capability counts/linkouts in the timeline.  It never makes an unavailable
slide viewable merely because a canonical source row said it should be.

New exports should use ``export_databricks_wsi_snapshot.py`` (which generates
both files from the same rows); this command is intended for repairing a
previously materialized study before re-importing its clinical timeline.
"""

from __future__ import annotations

import argparse
import csv
import os
import urllib.parse
from collections import defaultdict
from pathlib import Path
from typing import Any


def _rows(path: Path):
    with path.open(encoding="utf-8", newline="") as handle:
        lines = (line for line in handle if line.strip() and not line.startswith("#"))
        yield from csv.DictReader(lines, delimiter="\t")


def _truthy(value: Any) -> bool:
    return str(value or "").strip().upper() in {"TRUE", "1", "YES"}


def _group_key(
    patient_id: str,
    sample_id: str,
    match_level: str,
    specimen_key: str,
    stain_filter: str,
) -> tuple[str, str, str, str, str]:
    return (
        patient_id,
        sample_id,
        match_level.upper(),
        specimen_key,
        stain_filter.lower(),
    )


def _build_capability_groups(
    wsi_path: Path,
) -> dict[tuple[str, str, str, str, str], dict[str, bool]]:
    """Return one final capability flag per image and linkout key."""
    groups: dict[tuple[str, str, str, str, str], set[tuple[str, bool]]] = defaultdict(set)
    for row in _rows(wsi_path):
        patient_id = (row.get("PATIENT_ID") or "").strip()
        image_id = (row.get("IMAGE_ID") or "").strip()
        if not patient_id or not image_id:
            raise ValueError("WSI data contains an empty patient or image id")
        sample_id = (row.get("SAMPLE_ID") or "").strip()
        match_level = (row.get("MATCH_LEVEL") or "").strip().upper()
        specimen_key = (row.get("SPECIMEN_KEY") or "").strip()
        if not match_level or not specimen_key:
            raise ValueError(f"WSI row {image_id} has no match/specimen key")
        capability = _truthy(row.get("CAN_SERVE_TILES"))
        for stain_filter, include in (
            ("all", True),
            ("hne", _truthy(row.get("IS_HNE"))),
            ("ihc", _truthy(row.get("IS_IHC"))),
        ):
            if include:
                groups[_group_key(patient_id, sample_id, match_level, specimen_key, stain_filter)].add(
                    (image_id, capability)
                )

    return {
        key: {image_id: capable for image_id, capable in values}
        for key, values in groups.items()
    }


def _linkout_key(linkout: str) -> tuple[str, str, str, str, str] | None:
    parsed = urllib.parse.urlparse(linkout)
    if parsed.path != "/patient/wsiHESlides":
        raise ValueError(f"unsupported pathology linkout path: {parsed.path}")
    query = urllib.parse.parse_qs(parsed.query)
    patient_id = query.get("caseId", [""])[0]
    sample_id = query.get("sampleId", [""])[0]
    match_level = query.get("matchLevel", [""])[0]
    specimen_key = query.get("specimenKey", [""])[0]
    stain_filter = query.get("stainFilter", ["all"])[0].lower()
    if not patient_id or not match_level or not specimen_key:
        raise ValueError("pathology linkout is missing a stable matching parameter")
    return _group_key(patient_id, sample_id, match_level, specimen_key, stain_filter)


def reconcile(
    wsi_path: Path,
    timeline_path: Path,
    *,
    check_only: bool = False,
    unresolved_as_non_servable: bool = False,
    drop_unresolved: bool = False,
) -> dict[str, int]:
    groups = _build_capability_groups(wsi_path)
    used_images: dict[str, set[str]] = defaultdict(set)
    changed = 0
    linkouts_removed = 0
    rows_seen = 0
    temporary = timeline_path.with_suffix(timeline_path.suffix + ".tmp")
    with timeline_path.open(encoding="utf-8", newline="") as source:
        reader = csv.DictReader(source, delimiter="\t")
        if not reader.fieldnames:
            raise ValueError("timeline file has no header")
        fieldnames = list(reader.fieldnames)
        required = {"IMAGE_COUNT", "NON_SERVABLE_IMAGE_COUNT", "TOTAL_IMAGE_COUNT", "LINKOUT"}
        if not required.issubset(fieldnames):
            raise ValueError("timeline file is missing capability columns")
        output = None
        if not check_only:
            output = temporary.open("w", encoding="utf-8", newline="")
            writer = csv.DictWriter(output, fieldnames=fieldnames, delimiter="\t", lineterminator="\n")
            writer.writeheader()
        try:
            for row in reader:
                rows_seen += 1
                linkout = (row.get("LINKOUT") or "").strip()
                if linkout:
                    key = _linkout_key(linkout)
                    if key not in groups:
                        if drop_unresolved:
                            # The association is not present in the final WSI
                            # hierarchy at all. Drop the event rather than
                            # inventing a non-servable slide count that would
                            # make the timeline larger than the hierarchy.
                            changed += 1
                            continue
                        if not unresolved_as_non_servable:
                            raise ValueError(
                                "pathology linkout does not resolve to a WSI association"
                            )
                        # The event still describes a retained pathology
                        # record, but its slide is absent from the final WSI
                        # hierarchy. Treat every such image as non-servable
                        # and remove the unusable linkout.
                        old_total = int(row.get("TOTAL_IMAGE_COUNT") or 0)
                        old = (
                            row.get("IMAGE_COUNT", ""),
                            row.get("NON_SERVABLE_IMAGE_COUNT", ""),
                            row.get("TOTAL_IMAGE_COUNT", ""),
                            linkout,
                        )
                        row["IMAGE_COUNT"] = "0"
                        row["NON_SERVABLE_IMAGE_COUNT"] = str(old_total)
                        row["TOTAL_IMAGE_COUNT"] = str(old_total)
                        row["LINKOUT"] = ""
                        linkouts_removed += 1
                        changed += old != (
                            row["IMAGE_COUNT"],
                            row["NON_SERVABLE_IMAGE_COUNT"],
                            row["TOTAL_IMAGE_COUNT"],
                            row["LINKOUT"],
                        )
                        if output is not None:
                            writer.writerow(row)
                        continue
                    group_images = groups[key]
                    # A legacy timeline can contain duplicate events for one
                    # physical image (for example overlapping ``all`` stain
                    # groups). Assign an image to its first event only; the
                    # final timeline must never count it twice.
                    remaining_images = {
                        image_id: capable
                        for image_id, capable in group_images.items()
                        if image_id not in used_images[key[0]]
                    }
                    used_images[key[0]].update(remaining_images)
                    servable = sum(remaining_images.values())
                    non_servable = len(remaining_images) - servable
                    total = len(remaining_images)
                    if total == 0:
                        changed += 1
                        continue
                    old = (
                        row.get("IMAGE_COUNT", ""),
                        row.get("NON_SERVABLE_IMAGE_COUNT", ""),
                        row.get("TOTAL_IMAGE_COUNT", ""),
                        linkout,
                    )
                    row["IMAGE_COUNT"] = str(servable)
                    row["NON_SERVABLE_IMAGE_COUNT"] = str(non_servable)
                    row["TOTAL_IMAGE_COUNT"] = str(total)
                    if servable == 0:
                        row["LINKOUT"] = ""
                        linkouts_removed += 1
                    if old != (
                        row["IMAGE_COUNT"],
                        row["NON_SERVABLE_IMAGE_COUNT"],
                        row["TOTAL_IMAGE_COUNT"],
                        row.get("LINKOUT", ""),
                    ):
                        changed += 1
                if output is not None:
                    writer.writerow(row)
        finally:
            if output is not None:
                output.close()
    if not check_only:
        os.replace(temporary, timeline_path)
    return {
        "wsi_groups": len(groups),
        "timeline_rows": rows_seen,
        "rows_changed": changed,
        "linkouts_removed": linkouts_removed,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wsi-file", type=Path, required=True)
    parser.add_argument("--timeline-file", type=Path, required=True)
    parser.add_argument("--check-only", action="store_true")
    parser.add_argument(
        "--unresolved-as-non-servable",
        action="store_true",
        help=(
            "repair legacy events whose linkout is absent from the final WSI "
            "snapshot; use only when repairing an existing release"
        ),
    )
    parser.add_argument(
        "--drop-unresolved",
        action="store_true",
        help=(
            "repair mode: omit timeline events whose association is absent "
            "from the final WSI hierarchy"
        ),
    )
    args = parser.parse_args()
    result = reconcile(
        args.wsi_file,
        args.timeline_file,
        check_only=args.check_only,
        unresolved_as_non_servable=args.unresolved_as_non_servable,
        drop_unresolved=args.drop_unresolved,
    )
    print(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
