name: Update MySQL Docker Image on New Release

on:
  push:
    paths:
      - '.env'
  workflow_dispatch:

jobs:
  update-mysql-docker-image:
    runs-on: ubuntu-latest
    if: github.repository == 'cbioportal/cbioportal-docker-compose'
    env:
      CBIOPORTAL_TEST_REPO: 'cbioportal/cbioportal-test'
      DOCKERHUB_REPO: 'cbioportal/mysql'
      PLATFORMS: 'linux/amd64,linux/arm64'
      DUMP_PATH: '/cbioportal-test/dump.sql'
      DEFAULT_STUDY: 'lgg_ucsf_2014'
    steps:
      - name: Checkout cbioportal-docker-compose
        uses: actions/checkout@v4
        with:
          path: cbioportal-docker-compose
      - name: Checkout cbioportal-test
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CBIOPORTAL_TEST_REPO }}
          path: cbioportal-test
      - name: Parse cbioportal version
        id: parse_version
        run: |
          cd cbioportal-docker-compose
          VERSION=$(grep DOCKER_IMAGE_CBIOPORTAL .env | tail -n 1 | cut -d '=' -f 2-)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Use base mysql image
        run: |
          cd cbioportal-docker-compose
          sed -i 's|^DOCKER_IMAGE_MYSQL=.*|DOCKER_IMAGE_MYSQL=mysql:8.0|' .env
      - name: Run cBioPortal in background
        run: |
          cd cbioportal-docker-compose
          ./init.sh
          docker compose up -d
      - name: Wait for cBioPortal to be ready
        run: |
          cd cbioportal-test
          ./utils/check-connection.sh --url=localhost:8080 --interval=5 --max_retries=30 --insecure=false
      - name: Import default study
        run: |
          cd cbioportal-docker-compose
          docker compose exec cbioportal metaImport.py -u http://cbioportal:8080 -s study/$DEFAULT_STUDY/ -o
      - name: Dump overloaded mysql
        run: |
          cd cbioportal-test
          chmod +x scripts/dump-data.sh
          ./scripts/dump-data.sh --url=localhost:8080 --out=$DUMP_PATH
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU flags
        run: |
          # Avoid segmentation faults, check https://github.com/docker/buildx/issues/1170#issuecomment-1159350550
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes
      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: cbioportal-test/
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:8.0-cbioportal-v${{ steps.parse_version.outputs.version }}
          build-args: |
            DUMP_PATH=${{ env.DUMP_PATH }}
            STUDY_NAMES=${{ env.DEFAULT_STUDY }}
          file: cbioportal-test/docker/cbioportal-database.Dockerfile
          cache-from: type=gha
          cache-to: type=gha